title: Cobre, negros y alemanes
subtitle: Cátalogo del Museo del Oro y de la Plata
author:
  name: Wax user
  email: your-email@domain.com
description:
  Un caso que combina minería y azúcar es el de los Welser de Alemania. Esta compañía alemana desde 1525 posee privilegio
  para establecer un ingenio en La Española  para lo cual impornt grandes cantidades de negros.
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://pkulstad.github.io"
baseurl: "/minicomp"

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  minicomp: # name of collection
    output: true # makes sure pages are output as html files
    layout: "minicomp_item" # the layout for the pages to use
    metadata:
      source: "minicomp.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/minicomp" # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      minicomp:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - code
          - objeto
          - object_type
          - _date_manufacture
          - object_type_eng
          - place_manufacture
          - place_manufacture_eng
          - site_provenience

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "Exhibits"
    sub:
      - label: "Parallax Images"
        link: "/exhibits/parallax/"
      - label: "Image References"
        link: "/exhibits/references/"
      - label: "Subset Collection"
        link: "/exhibits/subset/"
  - label: "Browse"
    link: "/collection/"
  - label: "Search"
    link: "/search/"
  - label: "How To"
    link: "/learning/"
  - label: "About"
    link: "/about/"
